export const PROMPT_TYPES = {
    TABOO: 'taboo',
    DONATE: 'donate',
    READ: 'read',
    IDENTIFY: 'identify',
    PRICE: 'price',
    SITUATION: 'situation',
    TIBS: 'tibs',
    TRANSLATE: 'translate',
    SURVEY_QUESTION_COUNTRY: 'survyQuestionCountry',
    COUNTRY_RECOMMENDATION: 'countryRecommendation',
    ENVIRONMENTAL_IMPACT: 'environmentalImpact',
    NEXT_QUESTION_COUNTRY: 'nextQuestionCountry',
    NEXT_QUESTION_ENVIRONMENT: 'nextQuestionEnvironment',
    TRANSLATE_APP: 'translateApp',
    AUDIO_TRANSCRIPTION:"audioTranscription",
    AUDIO_COMMAND:"audioCommand",
  };