export const PROMPT_TYPES = {
  TABOO: "taboo",
  DONATE: "donate",
  READ: "read",
  IDENTIFY: "identify",
  PRICE: "price",
  SITUATION: "situation",
  TIBS: "tibs",
  TRANSLATE: "translate",
  SURVEY_QUESTION_COUNTRY: "survyQuestionCountry",
  COUNTRY_RECOMMENDATION: "countryRecommendation",
  ENVIRONMENTAL_IMPACT: "environmentalImpact",
  NEXT_QUESTION_COUNTRY: "nextQuestionCountry",
  NEXT_QUESTION_ENVIRONMENT: "nextQuestionEnvironment",
  TRANSLATE_APP: "translateApp",
  TRANSLATE_PRIORITY: "translatePriority",
  AUDIO_COMMAND: "audioCommand",
  COUNTRY_DATA: "countryData",
  AI_QUESTION: "aiQuestion",
  VOICE_TO_TEXT: "voiceToText",
};
